### ISSUE TITLE
Formatter adds a space to start of block scope

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#2932] opened 2022-10-04 11:35 UTC
The following code, when formatted, will add a space after the `foo` declaration line but right before the `{` so that it becomes ` <space>{`.
```rust
library scope;

fn shadowing_by_scope() {
    // ANCHOR: shadowing
    let foo = 5;
    {
        let foo = 42;
    }
    assert(foo == 5);
    // ANCHOR_END: shadowing
}
```

Post formatting:

```rust
library scope;

fn shadowing_by_scope() {
    // ANCHOR: shadowing
    let foo = 5;
     {
        let foo = 42;
    }
    assert(foo == 5);
    // ANCHOR_END: shadowing
}
```

**Comment by yash251** [comment] 2022-12-21 10:34
which file is this code in?

**Comment by Braqzen** [comment] 2022-12-21 11:31
> which file is this code in?

The code can be found [here](https://github.com/FuelLabs/sway/blob/master/docs/reference/src/code/language/variables/src/lib.sw); however, if you take a look at this issue and that code you will notice that there is no space because it has been manually removed.

This is one example that you may use when trying to fix the issue in the sway formatter. Alternatively, the snippet has been posted in the issue as a minimal reproducible sample so you should be able to create a brand new `forc` project and paste the code from the issue in there. If you run the formatter, assuming it hasn't been fixed since this issue was posted, then the snippet should "break" into the `post-formatting` sample. If that is the case then some code inside the formatter needs to be fixed.

**Comment by AliJafriETH** [comment] 2022-12-26 11:46
Hey @Braqzen, is this issue still open?

**Comment by bingcicle** [comment] 2023-01-13 06:40
Hey @AliJafriETH, I can confirm that the issue still exists on the `master` version of the formatter. Would you like to have a shot at this?

**Comment by AliJafriETH** [comment] 2023-01-13 10:06
Hey @bingcicle, thank you so much 👍 
Would love to work on the issue, might take some time as i'm currently having my uni exams :'(

**Comment by bingcicle** [comment] 2023-01-13 10:15
@yash251 - are you still working on the issue? If so, do let us know if you encountered any blockers.

@AliJafriETH since the issue was assigned to @yash251 initially, I'd like to first see if @yash251 would like to continue working on it first, so that we don't end up wasting your time doing duplicate work. :/

**Comment by bingcicle** [comment] 2023-01-13 11:06
@AliJafriETH I see now that you're also assigned to https://github.com/FuelLabs/sway/issues/3474, perhaps you might want to focus on that first?

**Comment by AliJafriETH** [comment] 2023-01-29 19:51
Hey @bingcicle, just submitted the PR for #3474, is this issue still open?
Thanks 👍

**Comment by bingcicle** [comment] 2023-01-30 09:42
@AliJafriETH first of all, thanks for your PRs! Yes, if the issue isn't assigned to someone else or if they don't have a PR open that closes them, you can safely assume that it's still open. In this case since the issue is assigned to you, you can be relatively sure that no one will frontrun your PR :smile: 

With that said, I took a look at the PRs and it seemed like there are some misunderstandings about the requirements of the issue - please take a look at @eureka-cpu's comment [here](https://github.com/FuelLabs/sway/pull/3918#issuecomment-1407786155).

I would also recommend looking at some of the recent PRs to the formatter to see how you could make the same changes as well - this latest PR by @eureka-cpu fixing a bug could be a good starting point: https://github.com/FuelLabs/sway/pull/3915.

Please feel free to ask questions!

**Comment by yash251** [comment] 2023-01-30 11:52
where can I find it's reference in the sway book?

https://fuellabs.github.io/sway/v0.33.1/book/basics/variables.html

**Comment by bingcicle** [comment] 2023-02-07 14:23
Hey @yash251, following up from your [forum question](https://forum.fuel.network/t/not-able-to-understand-the-requested-changes-github-issue/1780) here:

Basically, in the original example posted in this issue, the code should not be changed at all, since the formatting is correct.

However, the formatter is currently putting a space right before the 2nd opening curly brace, after the statement `let foo = 5;`.

The diff (red is what we don't want, green is what we want - you can see there's an extra space inserted before the curly brace).

```diff
library scope;

fn shadowing_by_scope() {
    // ANCHOR: shadowing
    let foo = 5;
-     {
+   {
        let foo = 42;
    }
    assert(foo == 5);
    // ANCHOR_END: shadowing
}
```

The entire formatter lives within `swayfmt`, so getting to know that directory should be enough. It does use `sway-parse` and `sway-ast` to parse and understand the AST, but that shouldn't be in scope for this issue. There is a `Format` trait implemented for tokens that the formatter is interested in formatting, and within their implementations you will find how they're formatted. The [ItemFn impl](https://github.com/FuelLabs/sway/blob/master/swayfmt/src/items/item_fn/mod.rs) should probably be what you want here.

Please feel free to ask follow-up questions here!

**Closed** 2023-08-23 22:12 UTC
Labels: bug, good first issue, formatter
