### ISSUE TITLE
Generic type not accepted as function return type

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#782] opened 2022-02-13 01:26 UTC
The following library fails to compile since `T` isn't recognized as a type.

```rust
library foo;

pub enum Foo<T> {
    A: T,
}

impl Foo<T> {
    fn bar(self) -> T {
    }
}
```

```console
error
  --> return/src/main.sw:8:21
   |
 6 | 
 7 | impl Foo<T> {
 8 |     fn bar(self) -> T {
   |                     ^^ Unknown type name.
 9 |     }
10 | }
   |
```

**Comment by emilyaherbert** [comment] 2022-03-02 19:54
Closing as a duplicate of #814.

**Closed by emilyaherbert** 2022-03-02 19:54 UTC
Labels: bug, compiler
