### ISSUE TITLE
Add a `forc fmt` check to CI for `sway-lib-std`

### ISSUE THREAD

**Issue by eureka-cpu** [FuelLabs/sway#3871] opened 2023-01-24 06:32 UTC
Seems we're only checking the examples directory atm

**Comment by mohammadfawaz** [comment] 2023-01-24 09:06
Duplicate of https://github.com/FuelLabs/sway/issues/3871 - will close this one if that's okay with you @eureka-cpu

**Closed by mohammadfawaz** 2023-01-24 09:06 UTC
Labels: ci, lib: std, formatter
