### ISSUE TITLE
`Option::None` needs type argument

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway#3376] opened 2022-11-16 19:23 UTC
Using `forc 0.31.1` to compile a contract, the following error comes up:
```
|    storage.deposits.insert((sender, auction_id), Option::None);
|                                                          ^^^^ This parameter was declared as type Option<AuctionAsset>, but argument of type Option<T> was provided.
```

I tried the following:
- Assigning `Option::None` to a variable and pass that instead
  - Same type error as above
- Providing a type by using `Option<AuctionAsset>::None`
  - ```
    |    storage.deposits.insert((sender, auction_id), Option<AuctionAsset>::None);
    |                                                                     ^ Expected `,`.
     ```

**Comment by emilyaherbert** [comment] 2022-11-16 20:31
Duplicate of #3330.

**Closed by emilyaherbert** 2022-11-16 20:31 UTC
Labels: bug, compiler
