### ISSUE TITLE
`forc deploy` - consider generating "deployment" logs under a dedicated directory

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3445] opened 2022-11-28 08:48 UTC
Purely for debugging / easy access, it could be useful to generate a log for each deployment under some dedicated directory.

Logged info might include:

- datetime
- salt (if used)
- config-time const values (if relevant) (see [here](https://github.com/FuelLabs/sway-rfcs/pull/19))
- contract ID

Some considerations:

- These should be separate from the `out` directory as users may wish to commit these to their repository.
- Should we consider making this a user-specific log, and storing these under `~/.forc/` instead? It's not clear if these should remain a part of the development/project repository itself.
- We should avoid encouraging users to use these logs as a part of their app. They would specifically be a debug / informative tool for development - apps should user an indexer or custom tool if they want to track deployments reliably.

**Comment by nfurfaro** [comment] 2022-11-30 15:09
See https://github.com/wighawag/hardhat-deploy#savedeployments for inspiration.

**Comment by JoshuaBatty** [comment] 2023-08-31 05:48
duplicate of #4744 . Closed with #4913

**Closed by JoshuaBatty** 2023-08-31 05:48 UTC
Labels: enhancement, forc, forc-client
