### ISSUE TITLE
The contract function returns wrong value

### ISSUE THREAD

**Issue by chlenc** [FuelLabs/sway#5768] opened 2024-03-25 13:14 UTC
### Summary

During the development of Spark Perps, we encountered a peculiar bug where the contract function `vault::get_free_collateral_by_token()` returns an incorrect value. Despite hardcoding a value within the function for testing, the returned value does not match the expected hardcoded value. This issue seems to be related to how `forc` compiles the contract, as the discrepancy is observed both in local tests and on the beta-5 test network.

### Steps to Reproduce

1. Clone the Spark Perps repository and check out the branch with the reported issue (if you don't have a dotup, message me on t.me/defi_defiler):
    ```bash
    git clone git@github.com:compolabs/spark-perps.git
    cd spark-perps
    git checkout bug-failed-collateral-test
    forc build
    cargo test --package spark-perps --test integration_tests -- get_free_collateral::get_free_collateral_test --exact --nocapture
    ```

2. Observe the output of the `get_free_collateral::get_free_collateral_test` which demonstrates the incorrect return value from the contract function.

### Detailed Description

The function `get_free_collateral_by_token` is expected to return a hardcoded value of `2063986620` for testing purposes. However, the test logs indicate a returned value of `4000000000`, suggesting a discrepancy in the function's execution or return process.

- Hardcoded function for reference:
    ```rust
    #[storage(read)]
    fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
        let mut amount = 0;
        amount = get_free_collateral_by_token(trader, token);
        amount = 2063986620;
        return amount;
    }
    ```

- Observation: Commenting out the line `amount = get_free_collateral_by_token(trader, token);`, rebuilding the contract, and rerunning the test yields the expected hardcoded value:
    ```rust
    #[storage(read)]
    fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
        let mut amount = 0;
        // amount = get_free_collateral_by_token(trader, token);
        amount = 2063986620;
        return amount;
    }
    ```

### Toolchain Configuration

- `fuel-toolchain.toml`:
    ```toml
    [toolchain]
    channel = "latest-aarch64-apple-darwin"

    [components]
    forc = "0.49.3"
    fuel-core = "0.22.1"
    ```

### Additional Information

This issue may point towards a potential bug in the `forc` compiler or the way it handles function returns. Any insights or fixes would be greatly appreciated.

Thank you for your attention to this matter.

Alex, Composability labs

**Comment by ironcev** [comment] 2024-03-25 18:50
Out of a quick glance at the function, `get_free_collateral_by_token` is an endlessly recursive function. Sway does not support recursions at moment and actually I would expect a compiler error here saying that the function is recursive. However, even if  recursions were supported, the above definition would lead to endless recursion means running the code until running out of gas.

**Comment by chlenc** [comment] 2024-03-26 08:51
I assure you, there is no recursion, the function that I showed you is in the imlp block, the function that appears is outside this block if you rename it, so nothing will change.

```rs

#[storage(read)]
fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
    let mut amount = 0;
    amount = get_free_collateral_by_token_test(trader, token);
    amount = 2063986620;
    return amount;
}

```

**Comment by Dentosal** [comment] 2024-03-26 15:16
This indeed looks like a miscompilation bug. Have you been able to minimize the example for reproduction? We need source code for `get_free_collateral_by_token `at least.

> check the code please https://github.com/compolabs/spark-perps/blob/bug-failed-collateral-test/vault/src/main.sw#L105

I cannot access that code, is the repo private?

**Comment by chlenc** [comment] 2024-03-26 18:06
@Dentosal 
Yes, it’s private 
Just shared an access

**Comment by Dentosal** [comment] 2024-03-27 03:09
@ironcev the function is not self-recursive, as that's inside an `impl` block and calls a second function. This indeed is a miscompile. I reproduced it locally as well.

I was able to minimize the called function inside the codebase to this while still keeping the same miscompile:

```sway
#[storage(read)]
fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
    let proxy_contract = abi(ProxyContract, PROXY_ADDRESS.into());
    let spark_contracts = proxy_contract.get_spark_contracts();
    let vault_contract = abi(VaultContract, spark_contracts.vault_address.into());
    let _ = vault_contract.get_collateral_balance(trader, SETTLEMENT_TOKEN);
    1
}
```

where 

```sway

storage {
    collaterals: StorageMap<(Address, AssetId), u64> = StorageMap {},
}

impl ... {
    #[storage(read)]
    fn get_collateral_balance(trader: Address, token: AssetId) -> u64 {
        storage.collaterals.get((trader, token)).try_read().unwrap_or(0)
    }
}
```

Curiously, rewriting the original function to:

```sway
    #[storage(read)]
    fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
        let mut amount = 0;
        asm(amount: amount) { log amount zero zero zero; };
        amount = get_free_collateral_by_token2(trader, token);
        asm(amount: amount) { log amount zero zero zero; };
        amount = 2063986620;
        asm(amount: amount) { log amount zero zero zero; };
        return amount;
    }
```

Logs the following values for amount: `0`, `1`, `2063986620`, so the register/variable is updated correctly, the function just returns an incorrect value.

Looking into `forc build --finalized-asm`, I just cannot see the log statements at all. Same with `forc parse-bytecode` from the output binary. Not sure if this has anything to do with the actual issue above, but seemed to be worth a mention.

Sadly this is far as I got. Someone from @FuelLabs/sway-compiler should pick this one up.

**Comment by dcpp** [comment] 2024-03-27 12:14
> @ironcev the function is not self-recursive, as that's inside an `impl` block and calls a second function. This indeed is a miscompile. I reproduced it locally as well.
> 
> I was able to minimize the called function inside the codebase to this while still keeping the same miscompile:
> 
> ```sway
> #[storage(read)]
> fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
>     let proxy_contract = abi(ProxyContract, PROXY_ADDRESS.into());
>     let spark_contracts = proxy_contract.get_spark_contracts();
>     let vault_contract = abi(VaultContract, spark_contracts.vault_address.into());
>     let _ = vault_contract.get_collateral_balance(trader, SETTLEMENT_TOKEN);
>     1
> }
> ```
> 
> where
> 
> ```sway
> storage {
>     collaterals: StorageMap<(Address, AssetId), u64> = StorageMap {},
> }
> 
> impl ... {
>     #[storage(read)]
>     fn get_collateral_balance(trader: Address, token: AssetId) -> u64 {
>         storage.collaterals.get((trader, token)).try_read().unwrap_or(0)
>     }
> }
> ```
> 
> Curiously, rewriting the original function to:
> 
> ```sway
>     #[storage(read)]
>     fn get_free_collateral_by_token(trader: Address, token: AssetId) -> u64 {
>         let mut amount = 0;
>         asm(amount: amount) { log amount zero zero zero; };
>         amount = get_free_collateral_by_token2(trader, token);
>         asm(amount: amount) { log amount zero zero zero; };
>         amount = 2063986620;
>         asm(amount: amount) { log amount zero zero zero; };
>         return amount;
>     }
> ```
> 
> Logs the following values for amount: `0`, `1`, `2063986620`, so the register/variable is updated correctly, the function just returns an incorrect value.
> 
> Looking into `forc build --finalized-asm`, I just cannot see the log statements at all. Same with `forc parse-bytecode` from the output binary. Not sure if this has anything to do with the actual issue above, but seemed to be worth a mention.
> 
> Sadly this is far as I got. Someone from @FuelLabs/sway-compiler should pick this one up.

You are right. Logs shows the function executes correctly by the end of one. But function's return value is not same as calculated inside of it.

**Comment by chlenc** [comment] 2024-03-28 18:01
gm frens, can you please give eta of the fix?

**Comment by IGI-111** [comment] 2024-03-29 05:56
We'll take a look as soon as possible but there are other critical issues right now so it'll at least take us some days to get to this one.

**Comment by chlenc** [comment] 2024-03-29 11:03
Thank you 
Waiting for solution!!!!!!!!!

**Comment by chlenc** [comment] 2024-04-01 09:33
Gm @IGI-111 
Are there any updates?

**Comment by chlenc** [comment] 2024-04-02 17:32
Hi frens
Can you give me info about timing when you solve this issue?

we can’t check our math with this bug

Is there any workaround?

**Comment by IGI-111** [comment] 2024-04-02 18:22
We're looking at it now, still no idea of the underlying cause and therefore of the timeline for a fix unfortunately.

**Comment by chlenc** [comment] 2024-04-02 21:46
Okay, thank you for reply 
Is it can be something because of complexity? 
Maybe can you suggest a direction and we try to fix it internally as well?
Waiting for a solution!!!

**Comment by jjcnn** [comment] 2024-04-05 09:39
@chlenc : This bug has now been assigned to me. Could you give me access to the repo, please?

**Comment by chlenc** [comment] 2024-04-05 09:51
@jjcnn 
https://github.com/compolabs/spark-perps/invitations

If you have any questions feel free to text me in telegram 
Https://T.me/defi_defiler

**Comment by jjcnn** [comment] 2024-04-05 10:21
Thanks. I'll see what I can find.

**Comment by IGI-111** [comment] 2024-04-13 05:17
Closing in favor of https://github.com/FuelLabs/fuels-rs/issues/1333

The VM and compiler are behaving correctly, this is an SDK issue.

**Closed by IGI-111** 2024-04-13 05:17 UTC
Labels: bug, compiler, P: critical
