### ISSUE TITLE
hash functions return 0 in some cases

### ISSUE THREAD

**Issue by IGI-111** [FuelLabs/sway#4951] opened 2023-08-14 16:04 UTC
Hash functions in this example return 0 instead of a usable value for an unknown reason.

https://github.com/Braqzen/wtf-is-this-wtf-is-that-why-does-the-hash-do-strange-things-why-are-we-even-here-what-is-life-rn

**Comment by esdrubal** [comment] 2023-08-16 09:01
I reproduced this issue on my end using the repo provided by Braqzen.

This issue is bizarre indeed, I could not find a fix but it does not seem to be related to the compiler.

The reason I say it is not related to the compiler is that the same bytecode works when the test uses fuels version 0.44.

Changed Cargo.toml:
```
fuels = { version = "0.44", features = ["fuel-core-lib"] }
```
Changed harnes.rs:
```rust
#[tokio::test]
async fn testing() {
    let mut wallets =
        launch_custom_provider_and_get_wallets(WalletsConfig::default(), None, None).await;
    let wallet = wallets.pop().unwrap();

    let script_call_handler = MyScript::new(wallet.clone(), SCRIPT_BINARY_PATH).main();

    let response = script_call_handler.call().await.unwrap();

    let mut hasher = Keccak256::new();
    hasher.update(response.value.0 .0);
    let hashed_id = hasher.finalize();

    dbg!(response.value.0);
    dbg!(hashed_id);
    dbg!(response.decode_logs().filter_succeeded());
    dbg!(response);

    // assert!(response.value);
    assert!(false);
}
```

**Comment by Braqzen** [comment] 2023-08-16 17:37
Note: I have bumped the Rust SDK to version `0.46`.

When I run the code in the repo with forc version `0.42.1` the hashing results in 0 values.
When I bump forc to `0.44` the hashes seem to no longer be 0, whether the values are correct remain to be tested.

**Comment by vaivaswatha** [comment] 2023-08-17 04:30
When I run `forc test -l` on this code, 

```
script;

use std::{constants::ZERO_B256, hash::keccak256, tx::tx_id};

fn main() -> (b256, b256) {
// fn main() -> b256 {
    let txid = tx_id();

    // log(txid);
    // log(keccak256(txid));

    (txid, keccak256(txid))
    // txid
    // keccak256(txid)
}

// Tests are meant to fail to see diff in values
#[test]
fn test_hash() {
   let id = tx_id();
   log(id);
   let hash = keccak256(id);
   log(hash);
   // assert_eq(hash, ZERO_B256);
}
```
I get

```
[
  {
    "LogData": {
      "data": "e3402c40b71c4b8b73175ad1cbe53afd366e6652d5c213e0e9ccba033efd2a61",
      "digest": "9263961b7066816921d3e8a3967670d5359543b4ed242f7e87fdf31bc6a0056c",
      "id": "0000000000000000000000000000000000000000000000000000000000000000",
      "is": 10344,
      "len": 32,
      "pc": 10512,
      "ptr": 10952,
      "ra": 0,
      "rb": 0
    }
  },
  {
    "LogData": {
      "data": "b6947d9f9045520daaf699039461763e5129147eb88f63503b1e9696d62dbb99",
      "digest": "8240bae4853d741b27c5c7d8e97b94bfbfb83f0739f0c2aedec5fa1c404be1d8",
      "id": "0000000000000000000000000000000000000000000000000000000000000000",
      "is": 10344,
      "len": 32,
      "pc": 10576,
      "ptr": 10920,
      "ra": 0,
      "rb": 1
    }
  }
]
```
and I computed `keccak256` of `e3402c40b71c4b8b73175ad1cbe53afd366e6652d5c213e0e9ccba033efd2a61` [online](https://emn178.github.io/online-tools/keccak_256.html), which said that its `b6947d9f9045520daaf699039461763e5129147eb88f63503b1e9696d62dbb99`. So it all looks fine to me.

**Comment by Braqzen** [comment] 2023-08-17 18:42
> 

Seems to work for hex, does not work for values such as `keccak256(1)`. That might be a different issue, padding

**Comment by vaivaswatha** [comment] 2023-08-18 04:28
> > 
> 
> Seems to work for hex, does not work for values such as `keccak256(1)`. That might be a different issue, padding

When you do `keccak256(1)`, that's a `1u64`, and keccak256(1u64)` is `6c31fc15422ebad28aaf9089c306702f67540b53c7eea8b7d2941044b027100f`, which is what the test prints. On the other hand  `keccak256(1u8)` also prints the same value, which is incorrect. 

I think that we could fix this since the `K256` opcode allows specifying length of the byte sequence to be hashed, and in this case it should be 1 byte, but is incorrectly generated as 8 bytes.

@IGI-111 shall we keep this Issue open to fix this? (and perhaps change the title?). It can stay assigned to me. I'll see what's the right fix.

**Closed** 2023-09-13 13:44 UTC
Labels: bug, P: critical
