### ISSUE TITLE
Sway formatting turns `+=` into `+ =` which breaks the `build` command because it is not a valid expression

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway#1945] opened 2022-06-11 13:50 UTC
# Reproduce

So, here is a fun error.
The following will build however you should use `forc fmt` to ensure that everything is formatted correctly.

```rust
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        let mut a = 1;
        a += 1;
        true
    }
}
```

The formatted file looks as follows

```rust
contract;

abi MyContract {
    fn test_function() -> bool;
}

impl MyContract for Contract {
    fn test_function() -> bool {
        let mut a = 1;
        a + = 1;
        true
    }
}
```

Notice that the `+=` has turned into `+ =`.
This means that you can format the code however you will break the `build` command because `+ =` is not a valid expression.

You have 3 options.

1. Pass the formatting check but break the build so it won't compile
2. Do not format your code and the CI will fail (but it will build if it were to get that far)
3. Do not use `+=` and instead use the long form.

# Screenshots
![1](https://user-images.githubusercontent.com/103777923/173190602-ff20c715-9c84-45f5-9e45-e4a700d6f53b.png)

cc @eureka-cpu

**Comment by mohammadfawaz** [comment] 2022-06-11 16:24
This is a serious issue and might even be worth fixing in the current formatted if v2 is not going to be ready soon. The alternative is to disallow `+=` and co until the issue is fixed and v2 is ready.

**Comment by kayagokalp** [comment] 2022-06-12 21:21
As it seems fairly easy to fix (a couple of lines), I am pushing a quick fix for this to the old formatter until we are ready with the formatter v2.

**Closed** 2022-06-12 23:04 UTC
Labels: bug, formatter, P: critical
