### ISSUE TITLE
Compiler fails to error when contract impl is incorrect

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#1311] opened 2022-04-19 21:09 UTC
Given this Sway contract:

```rust
contract;

storage {
    apples: u64
}

abi CounterContract {
    fn initialize();
    fn increment(n: u64);
    fn get() -> u64;
}

// error should be here
impl CounterContract {
    fn initialize() {
        storage.apples = 0;
    }

    fn increment(n: u64) {
        storage.apples = storage.apples + n;
    }

    fn get() -> u64 {
        storage.apples
    }
}
```

and this test file:

```rust
use fuel_tx::Salt;
use fuels_abigen_macro::abigen;
use fuels_contract::{contract::Contract, parameters::TxParameters};
use fuels_signers::util::test_helpers;

// Load abi from json
abigen!(CounterContract, "out/debug/counter_contract-abi.json");

async fn get_instance() -> CounterContract {

    // Build the contract
    let salt = Salt::from([0u8; 32]);
    let compiled = Contract::load_sway_contract("./out/debug/counter_contract.bin", salt).unwrap();

    // Launch a local network and deploy the contract
    let (provider, wallet) = test_helpers::setup_test_provider_and_wallet().await;
    let id = Contract::deploy(&compiled, &provider, &wallet, TxParameters::default())
        .await
        .unwrap();

    // retrieve the contract instance
    CounterContract::new(id.to_string(), provider, wallet)
}

#[tokio::test]
async fn increment_and_get() {
    let counter_contract = get_instance().await;

    counter_contract.initialize().call().await.unwrap();
    counter_contract.increment(99).call().await.unwrap();
    counter_contract.increment(1).call().await.unwrap();
    let apples = counter_contract.get().call().await.unwrap();

    assert_eq!(apples, 100);
}
```

everything builds and the compiler says that the contract file is OK, but then the test file fails to find the functions defined in the ABI. This was confusing and took me a few minutes to see my mistake. Either the compiler should fail to compile in this case or there should be a warning.

**Comment by mohammadfawaz** [comment] 2022-04-19 22:14
Oh so writing `impl CounterContract` instead of `impl CounterContract for Contract` compiles? Yeah that should be fixed.

**Comment by mohammadfawaz** [comment] 2022-05-04 02:48
Setting the priority to medium. This is, for the most part, is a usability issue.

**Comment by mohammadfawaz** [comment] 2022-08-04 18:28
I can't reproduce this anymore. I get the following error now:

```console
12 |
13 | // error should be here
14 | impl CounterContract {
   |      ^^^^^^^^^^^^^^^ Unknown type name "CounterContract".
15 |     fn initialize() {
16 |         storage.apples = 0;
```

which makes sense as `CounterContract` is not a type. This probably was fixed at some point with your changes to the type system @emilyaherbert. Closing!

**Closed by mohammadfawaz** 2022-08-04 18:28 UTC
Labels: bug, P: medium, compiler: ui
