### ISSUE TITLE
Internal Compiler Error: Unsupported constant expression type

### ISSUE THREAD

**Issue by Ferret-san** [FuelLabs/sway#1665] opened 2022-05-25 13:35 UTC
Encountered this error while trying to compile a predicate with `forc v0.13.1`. If you `forc init` a new project and try to compile the following predicate:

```
predicate;

use std::assert::assert;
use std::b512::B512;
use std::ecr::EcRecoverError;
use std::result::*;
use std::vm::evm::evm_address::EvmAddress;
use std::vm::evm::ecr::ec_recover_evm_address;

const OWNER = ~EvmAddress::from(0xe4eab8f844a8d11b205fd137a1b7ea5ede26f651909505d99cf8b5c0d4c8e9c1);

fn main() -> bool {
    //======================================================
    // test data from sig-gen-util: /sway/sig_gen_util/src/main.rs
    /**
    Secret Key: SecretKey(3b940b5586823dfd02ae3b461bb4336b5ecbaefd6627aa922efc048fec0c881c)
    Public Key: 1d152307c6b72b0ed0418b0e70cd80e7f5295b8d86f5722d3f5213fbd2394f36b7ce9c3e45905178455900b44abb308f3ef480481a4b2ee3f70aca157fde396a
    Fuel Address (sha2-256): 6ba48099f6b75cae5a403863ace6ee8dc03f75e7aebc58b819667477358ae677
    Ethereum pubkey hash (keccak256): e4eab8f844a8d11b205fd137a1b7ea5ede26f651909505d99cf8b5c0d4c8e9c1
    Message Hash: 8ddb13a2ab58f413bd3121e1ddc8b83a328f3b830d19a7c471f0be652d23bb0e
    Signature: 82115ed208d8fe8dd522d88ca77812b34d270d6bb6326ff511297766a3af1166c07204f554a00e49a2ee69f0979dc4feef07f7dba8d779d388fb2a53bc9bcde4
   */

    // Get the expected ethereum address
    // let pubkeyhash = ;
    //

    let msg_hash = 0x8ddb13a2ab58f413bd3121e1ddc8b83a328f3b830d19a7c471f0be652d23bb0e;

    // create a signature:
    let sig_hi = 0x82115ed208d8fe8dd522d88ca77812b34d270d6bb6326ff511297766a3af1166;
    let sig_lo = 0xc07204f554a00e49a2ee69f0979dc4feef07f7dba8d779d388fb2a53bc9bcde4;
    let signature: B512 = ~B512::from(sig_hi, sig_lo);

    // recover the address:
    let result: Result<EvmAddress, EcRecoverError> = ec_recover_evm_address(signature, msg_hash);
    let recovered_address = result.unwrap();

    recovered_address == OWNER
}
```

The compiler returns the following error:
![image](https://user-images.githubusercontent.com/31937514/170272427-39f3c334-0657-4b04-8639-3c04da5e5689.png)

Additionally, if you attempt to build [this predicate](https://github.com/Ferret-san/sway/blob/predicate_data/examples/metamask_predicate/src/main.sw)

You should get this a similar error:
![image](https://user-images.githubusercontent.com/31937514/170274778-f7e86cdb-e460-4e38-9730-b1bf4ceb8dae.png)

Note that this last error comes from `keccak256_with_offset<T>(param: T, offset: u8) -> b256`, which is a function that only exists in my branch.

**Comment by otrho** [comment] 2022-05-25 15:02
This is a dupe of #1619.

**Comment by mohammadfawaz** [comment] 2022-05-25 15:02
* As @otrho said, the first problem is expected at the moment. Ref: https://github.com/FuelLabs/sway/issues/1619. Eventually this will work, but for the time being, `const` can only be used with primitive types (i.e. no structs, enums, etc.)
* The second problem is weird, especially because the error points to the whole function.

**Comment by otrho** [comment] 2022-05-25 15:07
True.  That's why perhaps it'd be better to close the other one as a dupe of this.  It looks like the one issue, but perhaps the span is wrong somehow?

**Comment by Ferret-san** [comment] 2022-05-25 15:27
I figured the first error could have been something expected, so for (the predicate I linked above)[https://github.com/Ferret-san/sway/blob/predicate_data/examples/metamask_predicate/src/main.sw], the `const` is set to a primitive. 

The function in question can be found [here](https://github.com/Ferret-san/sway/blob/predicate_data/sway-lib-std/src/hash.sw#L44-L64)

Which gets called (here)[https://github.com/Ferret-san/sway/blob/predicate_data/examples/metamask_predicate/src/main.sw#L27], since I changed the `keccak256<T>` function to call `keccak256_with_offset<T>` with an offset of `0`

**Comment by otrho** [comment] 2022-05-30 06:16
I've found that if the RHS is a function call then the span points to the function definition rather than the const expr or its initialiser in particular.  I think this is a product of our AST function inlining -- the RHS is a `TypedExpression` which can be pretty much anything, and when it's a `FunctionApplication` the span is the inlined function definition.

**Closed** 2022-05-30 13:29 UTC
Labels: bug, compiler, P: critical
