### ISSUE TITLE
Allow the use of `const` with non-primitive types

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#996] opened 2022-03-22 19:24 UTC
Currently, when the `const` keyword is used, a literal is expected on the RHS of the declaration. It would be nice if we also allow things like:
```rust
const ETH_ID = ~ContractId::from(0x00..00);
```
I think this requires constant evaluation in the frontend due to the `from()` method call.

**Comment by otrho** [comment] 2022-03-22 22:20
Probably a dupe of #407.

**Comment by emilyaherbert** [comment] 2022-06-10 20:08
@vaivaswatha I noticed that `TypedDeclaration::ConstantDeclaration(..)` is never used in the code on `master`: https://github.com/FuelLabs/sway/blob/6f3f7421c9c171e0b169e3f4f6d0b268ad57b89b/sway-core/src/semantic_analysis/ast_node/declaration.rs#L27

In your PR for this issue, will you ensure that `TypedDeclaration::ConstantDeclaration(..)` is either used, or removed as dead code?

**Comment by otrho** [comment] 2022-06-11 00:40
Argh, we've (or at least @sezna and I) have known about this for a while.  We had them working initially, and then Alex introduced a semi-hack which meant they all became variable declarations (but I can't remember why).  This meant special casing in the IRgen though, and I think is suboptimal.

I'd like to see `const`s become `ConstantDeclarations` again, but we need to remember why we made the change in the first place.  I have a feeling it was for reasons which might not be a problem now that the type system has matured.

**Comment by vaivaswatha** [comment] 2022-06-11 02:07
> @vaivaswatha I noticed that `TypedDeclaration::ConstantDeclaration(..)` is never used in the code on `master`:
> 
> https://github.com/FuelLabs/sway/blob/6f3f7421c9c171e0b169e3f4f6d0b268ad57b89b/sway-core/src/semantic_analysis/ast_node/declaration.rs#L27
> 
> In your PR for this issue, will you ensure that `TypedDeclaration::ConstantDeclaration(..)` is either used, or removed as dead code?

It seems to be used here. https://github.com/FuelLabs/sway/blob/aecaad35522b722af0ab657ef940bc33672cebf0/sway-core/src/optimize.rs#L87. The core of what I'm writing is *inside* `compile_constant_expression` that gets called from here in `compile_constants`. So I wouldn't say it's dead, but maybe we could refactor to not have it. Let's see once I'm done with this feature (that'll be quite soon).

**Comment by otrho** [comment] 2022-06-11 02:46
I think we should keep them, because they're not really variable declarations, and we can keep IRgen simpler that way.

**Closed** 2022-06-13 04:59 UTC
Labels: enhancement, compiler, language feature, P: high
