### ISSUE TITLE
Investigate odd behavior of performance data 

### ISSUE THREAD

**Issue by Aztercrew** [FuelLabs/sway#5615] opened 2024-02-15 14:06 UTC
Now that we can visualize it, performance data has some odd patterns that might reflect bugs in how it's collected in or out of the compiler, namely that the bytecode size is always the same and that memory usage is always the same between different steps.

**Comment by IGI-111** [comment] 2024-02-16 18:09
Spam dupe of https://github.com/FuelLabs/sway/issues/5381

**Closed by IGI-111** 2024-02-16 18:09 UTC
