### ISSUE TITLE
Exhaustivity checker assumes catchall exists on an empty enum.

### ISSUE THREAD

**Issue by sezna** [FuelLabs/sway#3420] opened 2022-11-23 16:08 UTC
While looking at #3362, I compared that implementation to Rust's `Never` implementation. I saw Rust had some cool methods that utilized the exhaustivity checker to naturally express unreachability:

```rust
impl Never {
    /// Convert this `Never` into a value of a different type.
    ///
    /// Since a `Never` can never be constructed, this is valid for any `Sized`
    /// type.
    pub fn into_any<T>(self) -> T {
        match self {}
    }

    /// Convert this `Never` into a value of a different type.
    ///
    /// Since a `Never` can never be constructed, this is valid for any `Sized`
    /// type.
    pub fn to_any<T>(&self) -> T {
        match *self {}
    }
}
```

I tried adding it to @esdrubal's `Never` enum and got the below error:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/12157751/203593800-31743cb2-45c2-4d0b-b9ae-05298169defe.png">

I think this should be considered a bug in the exhaustivity checker, as `_` is not actually a reachable pattern here.

**Comment by emilyaherbert** [comment] 2022-11-23 18:00
Duplicate of #1679

**Closed by emilyaherbert** 2022-11-23 18:00 UTC
Labels: bug, P: medium, compiler: frontend
