### ISSUE TITLE
Host reference docs for `core` and `std` somewhere until we have a package index and `docs.rs` equivalent

### ISSUE THREAD

**Issue by mitchmindtree** [FuelLabs/sway#3172] opened 2022-10-27 13:11 UTC
This refers to the docs produced by `forc doc` which landed in #2869.

Perhaps we could host these on github pages and link to them from the book?

#1066 should probably be addressed first.

#865 vaguely discusses the idea of a more general package index / registry, we could be used to create a more general documentation index similar to docs.rs in the long run.

**Comment by mohammadfawaz** [comment] 2023-01-29 13:53
This seems a duplicate of https://github.com/FuelLabs/sway/issues/3549. Will close. @mitchmindtree feel free to re-open if you disagree :)

**Closed by mohammadfawaz** 2023-01-29 13:53 UTC
Labels: forc, lib: std, lib: core, documentation, forc-doc
