### ISSUE TITLE
Cannot find `eq` for a type in a constraint function

### ISSUE THREAD

**Issue by mohammadfawaz** [FuelLabs/sway#3351] opened 2022-11-11 17:56 UTC
Code:
```rust
script;

use core::ops::*;

struct MyStruct {
    x: u64,
    y: u64,
}

impl Eq for MyStruct {
    fn eq(self, other: Self) -> bool {
        self.x == other.x && self.y == other.y
    }
}

fn main() -> bool {
    let s = MyStruct {x : 42, y: 43 };
    foo(s);
    true
}

fn foo<T>(val: T)
where
    T: Eq
{
    assert(val == val);
}
```
The `==` in the `assert` shows up in IR as:
```
    pub fn eq_4(self !33: { u64, u64 }, other !34: { u64, u64 }) -> bool, !35 {
        entry(self: { u64, u64 }, other: { u64, u64 }):
        v0 = const bool undef
        ret bool v0
    }
```
which indicates that the frontend is handing IRGen an "empty" implementation of `eq` which is not what we expect here. I had to disable all optimizations in `lib.rs` to see this.

In any case, when running `forc run --unsigned`, the code reverts.

This doesn't seem to be a problem for primitive types...

**Comment by emilyaherbert** [comment] 2022-11-17 16:28
Duplicate of #3326.

**Closed by emilyaherbert** 2022-11-17 16:28 UTC
Labels: bug, P: critical, compiler: frontend
