### ISSUE TITLE
Type ascriptions throw away type information

### ISSUE THREAD

**Issue by emilyaherbert** [FuelLabs/sway#929] opened 2022-03-11 18:09 UTC
Given this Sway code:

```rust
script;

struct DoubleIdentity<T, F> {
  first: T,
  second: F,
}

fn main() -> bool {
  let a: DoubleIdentity<u8, u8> = DoubleIdentity {
    first: 1u8,
    second: 2u8,
  };
  true
}
```

This gets tokenized via the `ident ~ type_params?` rule: https://github.com/FuelLabs/sway/blob/cfeeecc59f685d63ff5007d8e6ab0f3cea2cb74e/sway-core/src/sway.pest#L182

Which is then parsed and the type params are thrown away: https://github.com/FuelLabs/sway/blob/cfeeecc59f685d63ff5007d8e6ab0f3cea2cb74e/sway-core/src/type_engine/type_info.rs#L94

**Comment by sezna** [comment] 2022-03-11 19:15
This is a dupe of #425

**Comment by emilyaherbert** [comment] 2022-03-11 19:23
Is this a duplicate? This issue is not referring to turbofish.

**Comment by sezna** [comment] 2022-03-11 20:24
Ah, I see, I misread, yes you're right.

**Comment by mohammadfawaz** [comment] 2022-03-15 15:37
Assigned this to you @emilyaherbert as it shows that it's in progress. Feel free to un-assign yourself if you're not actually working on it.

**Closed** 2022-03-25 06:07 UTC
Labels: bug, compiler
