### ISSUE TITLE
Error when testing and a contract function returns a StorageVec

### ISSUE THREAD

**Issue by rtomas** [FuelLabs/sway#4884] opened 2023-07-28 19:22 UTC
I have no problem in compiling the contract with that return function

`fn get_list() -> StorageVec<Identity>;`

When I try to run `cargo test` (the default test) it show me this error:
<img width="1228" alt="image" src="https://github.com/FuelLabs/sway/assets/944960/a789fabd-49f2-4295-bc78-3ccb1eec5477">

**Comment by Braqzen** [comment] 2023-07-28 19:54
A storage vec is basically a hashtable. You cannot return the entire memory from a contract. You need to transform into a vec and then return that.

I'm a bit confused as to why this compiles but I assume it's because it returns a storage key instead cc @IGI-111 
We should probably close this. I don't think there's an issue here

**Comment by IGI-111** [comment] 2023-08-01 02:55
StorageVecs are not a special type so we don't prevent you from doing this. It just doesn't make sense to try to return them from a contract.

Maybe we'll want to introduce an annotation that forbids decoding certain types, I think that might be useful but it's not a bug that you can't express that as it is, so yeah I'm closing this.

**Closed by IGI-111** 2023-08-01 02:55 UTC
