### ISSUE TITLE
Test fails depending on the existence of a log

### ISSUE THREAD

**Issue by SwayStar123** [FuelLabs/sway#6352] opened 2024-08-01 14:13 UTC
### Related Component

compiler

### Problem

The given test only passes if the logging of the result occurs (may not be limited to logging, could just be usage of the result in anyway), if the log call is commented out, the test fails

### Steps

```
#[test(should_revert)]
fn math_u64_pow_overflow_should_revert() {
    let _result = 2_u64.pow(64);
    log(_result);
}
```
forc test

### Installed components

```console
forc 0.62.0
```

**Comment by Dentosal** [comment] 2024-08-23 11:22
See https://github.com/FuelLabs/sway/pull/6452#issuecomment-2306881388 for a reproduction and output analysis.

**Comment by IGI-111** [comment] 2024-10-09 13:35
Duplicate of #4307

**Comment by IGI-111** [comment] 2024-10-09 13:35
Duplicate of #4307

**Closed by IGI-111** 2024-10-09 13:35 UTC
Labels: bug, triage
