### ISSUE TITLE
Internal compiler error on conditional assignment with StorageVec

### ISSUE THREAD

**Issue by mauricewbr** [FuelLabs/sway#4503] opened 2023-04-27 10:08 UTC
forc version 0.38.0

Returning `()` from a conditional assignment due to missing `return` despite `;` will result in internal compiler error when passing `result` to `StorageVec`.

Error message (althought the `get_[XXX]` has been 19, 39, and 1641 so far)
```
error: Internal compiler error: Verification failed: Type mismatch found for call to 'get_19'.
Please file an issue on the repository and include the code that triggered this error.
```

To reproduce: `forc build`

```Sway
contract;

use std::{
    storage::storage_vec::*,
};

abi MyContract {
    #[storage(read, write)]
    fn test_function() -> StorageKey<StorageVec<u32>>;
}

storage {
    foo: StorageVec<u32> = StorageVec {},
}

impl MyContract for Contract {
    #[storage(read, write)]
    fn test_function() -> StorageKey<StorageVec<u32>> {
        let res = bar(true, 5);
        storage.foo.push(1);
        return storage.foo;
    }
}

#[storage(read)]
fn bar(cond: bool, num: u32) -> u32 {
    let res: u32 = if cond {
        do_nothing(num);
    } else {
        do_nothing(num);
    };
    let result = storage.foo.get(res).unwrap().read();
    return 1;
}

fn do_nothing(num: u32) -> u32 {
    return num;
}
```

**Comment by vaivaswatha** [comment] 2023-09-26 05:13
@mauricewbr I just tried this on the latest compiler (`0.46.0`) and I'm only able to get type-mismatch errors (and not an "internal compiler error"). I tried slight modifications to see if I could repro the ICE but couldn't. Can you check with the latest compiler and update back here if the Issue persists?

**Comment by vaivaswatha** [comment] 2023-10-04 09:16
Closing this as I can't reproduce it anymore. @mauricewbr please reopen if necessary.

**Closed by vaivaswatha** 2023-10-04 09:16 UTC
Labels: bug, compiler: ir
