### ISSUE TITLE
Introduce `thiserror` to forc-pkg

### ISSUE THREAD

**Issue by kayagokalp** [FuelLabs/sway#3283] opened 2022-11-04 10:14 UTC
related to https://github.com/FuelLabs/sway/pull/3134#discussion_r1010055662

**Comment by mohammadfawaz** [comment] 2023-01-29 13:48
Is this a duplicate of https://github.com/FuelLabs/sway/issues/1201?

**Comment by eureka-cpu** [comment] 2023-07-26 16:27
Closing in favor of #4817

**Closed by eureka-cpu** 2023-07-26 16:27 UTC
Labels: forc, code quality, forc-pkg
