### ISSUE TITLE
Functions from the same `impl` block cannot see each other

### ISSUE THREAD

**Issue by rostyslavtyshko** [FuelLabs/sway#3064] opened 2022-10-18 14:18 UTC
Sometimes (not always). If a function refers to another function within `impl` block cannot see it

**Comment by mohammadfawaz** [comment] 2022-10-18 14:49
True - this seems to be a duplicate of https://github.com/FuelLabs/sway/issues/1548 so I'm going to close it. There is some ongoing work right now to introduce a collection phase that will help with all these dependencies issues.

**Closed by mohammadfawaz** 2022-10-18 14:49 UTC
Labels: language feature, P: medium
