### ISSUE TITLE
Compiler allows unconstrained impl type parameters.

### ISSUE THREAD

**Issue by adlerjohn** [FuelLabs/sway#1143] opened 2022-04-04 16:07 UTC
While implementing #1118, stumbled upon a bug: https://github.com/FuelLabs/sway/runs/5819569715?check_suite_focus=true

Note: the old codegen also errors, but with a different error.

**Comment by mohammadfawaz** [comment] 2022-04-04 17:26
Another instance of generic types leaking into IR.. all generic types should be resolved before IR generation. The error in the old codegen is likely just a symptom of the same problem.

**Comment by otrho** [comment] 2022-04-06 05:27
This was the smallest repro I could come up with:
```rust
script;

struct S { }

impl<T> S {
  fn use_asm(self, value: T) {
    asm(size: size_of::<T>()) {
      aloc size;
    };
  }
}

fn main() {
    (S{}).use_asm(true);
}
```

It appears that the ASM block isn't copying the T type.  Note that the bug didn't arise when just using a generic function, it seemed to need to be in a generic `impl`.

**Comment by otrho** [comment] 2022-04-06 05:35
Could be tackled alongside #1103 and/or maybe #1116?

**Comment by otrho** [comment] 2022-04-06 07:18
I have a feeling this is where it needs to be fixed, as the problem is the trait method hasn't resolved T: https://github.com/FuelLabs/sway/blob/9fde15ff4232ad71a81bc5fa913576124a0d64a4/sway-core/src/semantic_analysis/ast_node/declaration.rs#L578

But I'm not sure.  @emilyaherbert @sezna do you have any ideas?  What does that comment mean?

**Comment by sezna** [comment] 2022-04-06 13:58
That comment is pretty vague and I feel like I probably wrote it, sorry about that. I believe what I meant was that the methods in a trait declaration are stored as un-type-checked until the trait is implemented, since they could be relatively generic and not have all the necessary type info.

**Comment by otrho** [comment] 2022-04-07 04:48
I'm still not sure what the solution is here.  I think the issue is that the struct itself doesn't have any type parameters, only the impl.  So the monomorphisation process currently starts with 'generic' type mappings which get resolved via `copy_types()` but these are all instantiated by typed function decls, typed struct decls or typed enum decls.

In the above we need the same but for typed impl decls, which isn't quite the same..?  The line I quoted above with the comment is in a `TypedTraitDeclaration` but as you say, a trait's methods aren't type checked until instantiated.  I think we instantiate them as `TypedFunctionDeclaration`s but in the case of `f()` in my repro, `T` is not resolved.  But is this true for all trait methods or am I missing something?  Let me check...

**Comment by otrho** [comment] 2022-04-07 05:21
Now I'm starting to think this will be fixed by #948.  It's impossible to explicitly create a trait with generics at the moment, but that's pretty much what we do in this repro, I think?

**Comment by adlerjohn** [comment] 2022-04-07 12:54
Could we force the generic type to be in the struct declaration? In the code I'm writing for `Vec`, I expect the `RawVec` to be generic.

```rust
struct S<T> { }

impl<T> S<T> {
  fn f(self, value: T) {
    size_of::<T>();
  }
}
```

**Comment by mohammadfawaz** [comment] 2022-04-07 13:08
Wait, I thought that required. Generic structs should need type parameters... 
The code below with no type parameters on the struct declaration does not look sane to me:
```rust
struct S { }

impl<T> S {
  fn f(self, value: T) {
    size_of::<T>();
  }
}
```

**Comment by otrho** [comment] 2022-04-07 13:43
Aha, well, I thought it might work... the compiler doesn't complain but maybe it should.  Rust:

```
error[E0207]: the type parameter `T` is not constrained by the impl trait, self type, or predicates
 --> src/main.rs:5:6
  |
5 | impl<T> S {
  |      ^ unconstrained type parameter

For more information about this error, try `rustc --explain E0207`.

```

**Comment by otrho** [comment] 2022-04-08 04:53
@mohammadfawaz I don't think this is still critical?

**Comment by otrho** [comment] 2022-04-08 13:58
If it's blocking Vec that's only because you're trying to use the malformed declarations.  I think even if you give `RawVec` a `T` but don't use it, we still have the same problem.  Rust again:
```
  |
3 | struct S<T> { }
  |          ^ unused parameter
  |
  = help: consider removing `T`, referring to it in a field, or using a marker such as `PhantomData`
  = help: if you intended `T` to be a const parameter, use `const T: usize` instead
```
I think the solution is not to use `T` for `RawVec`, but instead include the item size as a field, and then alloc with that.  You're only needing `T` for `size_of` in there.  `Vec` can still have `T` as is...

**Comment by adlerjohn** [comment] 2022-04-08 14:00
Hm, interesting workaround. I'll investigate and report back.

**Comment by adlerjohn** [comment] 2022-04-09 23:11
Tried that and there's a problem! If I remove the generic on `RawVec`, then `Vec` is

```rust
pub struct Vec<T> {
    buf: RawVec,
    len: u64,
}
```

which now also results in a compiler error! I don't think there's any way to make specific methods generic if the struct itself is not generic, right?

**Comment by otrho** [comment] 2022-04-10 01:53
Hrmm, I guess the solution is to put a dummy `T` field into `RawVec` but not use it, just to get it to type check?

It seems we need pointers, so that `buf` could actually be a `*T`, etc.

This is kinda where `impl<T> S { ... }` makes sense to me, if the methods use `T` it shouldn't matter whether `S` does or not.

**Comment by adlerjohn** [comment] 2022-04-10 02:19
I considered that, but it's a very non-ideal workaround because it would fundamentally change the ABI representation of `Vec`s. It's also not obvious how to get an instance of a `T` without knowing anything about `T`.

**Comment by emilyaherbert** [comment] 2022-04-11 18:53
I believe that the example we are discussing here is malformed. In Rust the closest approximation is this:

```rust
use core::mem::size_of;

struct S { }

impl S {
  fn f<T>(self, value: T) {
    size_of::<T>();
  }
}

fn main() {
    (S{}).f(true);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f9858aca30c642a70975fb529d222609

I actually don't know if this will work in Sway or not. Is this what you had in mind for this issue @adlerjohn ?

**Comment by emilyaherbert** [comment] 2022-04-11 18:55
> Aha, well, I thought it might work... the compiler doesn't complain but maybe it should.

I think maybe this is the problem @otrho .

**Comment by emilyaherbert** [comment] 2022-04-11 18:56
From my understanding, impls with generics should only be valid if the struct/enum/trait has a generic type, otherwise function, specific generics should go in the type parameters of the associated method in the impl.

**Comment by emilyaherbert** [comment] 2022-04-11 18:57
Are you working on this @otrho ? If not, I'm happy to take it.

**Comment by adlerjohn** [comment] 2022-04-11 21:55
Is there a reason to forbid a struct from being generic even if non of its fields are generic? It doesn't seem to inherently hurt, and unlocks a way to do `Vec` without forcing the user to specify the generic type every single time they call a function.

**Comment by emilyaherbert** [comment] 2022-04-12 00:12
How about instead we allow the user to use Vec without having to specify the generics? I think that they should be allowed to omit the generics if the compiler is able to infer the types. The reason why this doesn't work now in the compiler is either due to a bug or due to the specific relevant inference algorithms not being implemented. I would have to dive into more to figure out what is missing.

Personally I don't think it would be a good user experience to allow users to add generics to structs that are basically no-ops.

**Comment by sezna** [comment] 2022-04-12 00:51
> Is there a reason to forbid a struct from being generic even if non of its fields are generic? It doesn't seem to inherently hurt, and unlocks a way to do Vec without forcing the user to specify the generic type every single time they call a function.

it just feels kinda messy right? monomorphization would be a no-op though as Emily said. Although being messy doesn't inherently mean it should be disallowed. 

In Rust, the `<T>` in vec ultimately resolves to this T:
https://docs.rs/rust-libcore/0.0.2/src/core/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-libcore-0.0.2/rust/src/libcore/ptr.rs.html#685

That `T` is just a constant pointer, i.e. what we are currently calling a `u64`. That's the difference between us and Rust here. And that generic in Rust's case isn't even really doing any type system magic, it just boils down to a raw pointer, basically a `u64` just like us...because of that, I'm kind of in favor of allowing the noop generic for this specific pattern, since we likely won't implement reference logic to the same degree of intensity that Rust has.

**Comment by sezna** [comment] 2022-04-12 00:55
Ah! This is exactly why Rust has `PhantomData`. For types that represent a type in an unsafe way and can't use the type system to represent it.

`PhantomData` is zero-sized but takes a type argument, signifying that the struct contains something of that type even if it is a raw pointer/`u64`. 

@adlerjohn you could take a stab at implementing `PhantomData`?

**Comment by sezna** [comment] 2022-04-12 21:29
After much discussion, we have decided to allow unused generics and not implement `PhantomData`.

**Comment by adlerjohn** [comment] 2022-04-12 22:02
> After much discussion

That, uh, one way of putting it :joy:

**Comment by SilentCicero** [comment] 2022-04-16 02:34
What is the current status of the situation with this issue?

**Comment by sezna** [comment] 2022-04-16 04:21
I'm working on it, ETA early next week.

**Comment by sezna** [comment] 2022-04-20 22:55
I've spent some time with this and I'm going to document my thoughts here, for my own sanity:

Right now, generic types are stored in a field's type. E.g., the following struct declaration: ```rust
struct Test<T> { a: T }
```
gets stored as (pseudo)
```rust
struct {
  name: Test,
  fields: [{name: a, type: T}]
}
```

Note that the type parameters themselves are not stored in the type. Just the fields. This means that if you declare a struct like this:
```rust
struct Foo<T> {}
```

Then you get a type like this:
```rust
struct {
  name: Foo,
  fields: []
}
```
Unfortunately, this means that you _need_ to use a type parameter in order for the type system to understand your type and not incorrectly consider the types the same.

My solution to this is going to be to change struct and enum types. They should contain the type parameters within their type info, and the fields should be references to those type parameters. This will require some reworking of monomorphization but should otherwise be a drop-in change.

**Comment by emilyaherbert** [comment] 2022-05-28 17:42
After https://github.com/FuelLabs/sway/pull/1746 it seems that the `Vec` library from https://github.com/FuelLabs/sway/pull/1118 successfully builds https://github.com/FuelLabs/sway/pull/1750. Are we able to close this issue?

**Comment by emilyaherbert** [comment] 2022-05-31 00:08
Closed by https://github.com/FuelLabs/sway/pull/1746

**Comment by emilyaherbert** [comment] 2022-05-31 00:25
Ah I see @sezna, I had added this line which was allowing it to pass: https://github.com/FuelLabs/sway/blob/7bae662ac48326fcdf2d2164ff6aaba635849fb7/test/src/e2e_vm_tests/test_programs/should_pass/language/vec/src/main.sw#L14

I'll reopen and investigate!

**Comment by emilyaherbert** [comment] 2022-05-31 22:32
@sezna  I forget where we left things after the sync call---am I writing the fix that disallows @otrho code? (i.e. disallows declaring a generic param on an impl, when the type implementing for does not take a generic param)

**Closed** 2022-06-15 15:20 UTC
Labels: bug, P: critical, compiler: frontend, compiler: parser
